# Generated by Django 5.2.6 on 2025-09-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('imdbID', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('img_url', models.TextField()),
            ],
        ),
    ]
