# Generated by Django 5.2.6 on 2025-09-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_avaliacao_rename_movie_filmeavaliado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmeavaliado',
            name='type',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='filme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api.filmeavaliado'),
        ),
    ]
