# Generated by Django 5.2.6 on 2025-09-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_filmeavaliado_type_avaliacao_filme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmeavaliado',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
